version: '3.4'
services:
  localstack:
    image: localstack/localstack
    ports:
      - 4566:4566
    volumes:
      - "./tmp/localstack:/tmp/localstack"
      - "./localstack:/docker-entrypoint-initaws.d"